routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

$this->group(['middleware' => ['auth'], 'namespace' => 'Admin', 'prefix' => 'admin'], function () {
    $this->any('historic-search', 'BalanceController@searchHistoric')->name('historic.search');
    $this->get('historic', 'BalanceController@historic')->name('admin.historic');
    $this->get('transfer', 'BalanceController@transfer')->name('balance.transfer');
    $this->post('transfer', 'BalanceController@transferStore')->name('transfer.store');
    $this->post('confirmTransfer', 'balancecontroller@confirmTransfer')->name('confirm.Transfer');
    $this->get('withdraw', 'BalanceController@withdraw')->name('balance.withdraw');
    $this->post('withdraw', 'BalanceController@withdrawStore')->name('withdraw.store');
    $this->get('/', 'AdminController@index')->name('admin.home');
    $this->get('balance', 'BalanceController@index')->name('admin.balance');
    $this->get('deposit', 'BalanceController@deposit')->name('balance.deposit');
    $this->post('deposit', 'BalanceController@depositStore')->name('deposit.store');
    $this->post('atualizar-perfil', 'PerfilController@profileUpdate')->name('profile.update');
    $this->get('meu-perfil', 'PerfilController@profile')->name('profile');
    $this->get('logout', 'PerfilController@logout')->name('logout');
    $this->get('posts', 'PostController@index')->name('posts');

    Route::resource('users', 'UserController');

    Route::resource('roles', 'RoleController');

    Route::resource('permissions', 'PermissionController');

    Route::resource('posts', 'PostController');
});

$this->get('/', 'HomeController@index')->name('home');

Auth::routes();

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Models\Balance;
use App\Models\Historic;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable;

    use HasRoles; 
    
    protected $guard_name = 'web';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'image',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function setPasswordAttribute($password)
    {   
        $this->attributes['password'] = bcrypt($password);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\UpdateProfileFormRequest;
use App\User;
use Auth;

//Importing laravel-permission models
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

//Enables us to output flash messaging
use Session;

class UserController extends Controller
{

    public function __construct() {
        $this->middleware(['auth', 'isAdmin']); //isAdmin middleware lets only users with a //specific permission permission to access these resources
    }

    
    /**
    * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function index() {
    //Get all users and pass it to the view
        $users = User::orderby('name')->paginate(8); 
        return view('users.index')->with('users', $users);
    }

    /**
    * Show the form for creating a new resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function create() {
    //Get all roles and pass it to the view
        $roles = Role::get();
        return view('users.create', ['roles'=>$roles]);
    }

    /**
    * Store a newly created resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */
    public function store(Request $request) {
    //Validate name, email and password fields
        $this->validate($request, [
            'name'=>'required|max:120',
            'email'=>'required|email|unique:users',
            'password'=>'required|min:6|confirmed'
        ]);

        $user = User::create($request->only('email', 'name', 'password')); //Retrieving only the email and password data

        $roles = $request['roles']; //Retrieving the roles field
    //Checking if a role was selected
        if (isset($roles)) {

            foreach ($roles as $role) {
            $role_r = Role::where('id', '=', $role)->firstOrFail();            
            $user->assignRole($role_r); //Assigning role to user
            }
        }        
    //Redirect to the users.index view and display message
        return redirect()->route('users.index')
            ->with('flash_message',
             'User successfully added.');
    }

    /**
    * Display the specified resource.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function show($id) {
        return redirect('users'); 
    }

    /**
    * Show the form for editing the specified resource.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function edit($id) {
        $user = User::findOrFail($id); //Get user with specified id
        $roles = Role::get(); //Get all roles

        return view('users.edit', compact('user', 'roles')); //pass user and roles data to view

    }

    /**
    * Update the specified resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function update(Request $request, $id) {
        $user = User::findOrFail($id); //Get role specified by id

    //Validate name, email and password fields  
        $this->validate($request, [
            'name'=>'required|max:120',
            'email'=>'required|email|unique:users,email,'.$id,
            'password'=>'required|min:6|confirmed'
        ]);
        $input = $request->only(['name', 'email', 'password']); //Retreive the name, email and password fields
        $roles = $request['roles']; //Retreive all roles
        $user->fill($input)->save();

        if (isset($roles)) {        
            $user->roles()->sync($roles);  //If one or more role is selected associate user to roles          
        }        
        else {
            $user->roles()->detach(); //If no role is selected remove exisiting role associated to a user
        }
        return redirect()->route('users.index')
            ->with('flash_message',
             'User successfully edited.');
    }

    /**
    * Remove the specified resource from storage.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function destroy($id) {
    //Find a user with a given id and delete
        $user = User::findOrFail($id); 
        $user->delete();

        return redirect()->route('users.index')
            ->with('flash_message',
             'User successfully deleted.');
    }
    
}

resources/views/users/create.blade.php
@extends('adminlte::page')

@section('title', 'Adicionar Usuário')

@section('content_header')
<h3><i class="fa fa-users"></i> Administrador de usuários<h3>
    @stop
    
    @section('content')
    <div class="box">
        <div class="box-header">
            <div class="box-body">
                <div class="panel panel-default">
                    <div class="table-responsive">
                        <div class='col-lg-6 col-lg-offset-4'>
                            
                            <h3><i class='fa fa-user-plus'></i> Adicionar Usuário</h3>
                            @include('admin.includes.alerts')
                            {{ Form::open(array('url' => 'admin/users')) }}
                            
                            <div class="form-group">
                                {{ Form::label('name', 'Nome') }}
                                {{ Form::text('name', '', array('class' => 'form-control')) }}
                            </div>
                            
                            <div class="form-group">
                                {{ Form::label('email', 'Email') }}
                                {{ Form::email('email', '', array('class' => 'form-control')) }}
                            </div>
                            
                            <div class='form-group'>
                                @foreach ($roles as $role)
                                {{ Form::checkbox('roles[]',  $role->id ) }}
                                {{ Form::label($role->name, ucfirst($role->name)) }}<br>
                                
                                @endforeach
                            </div>
                            
                            <div class="form-group">
                                {{ Form::label('password', 'Senha') }}<br>
                                {{ Form::password('password', array('class' => 'form-control')) }}
                                
                            </div>
                            
                            <div class="form-group">
                                {{ Form::label('password', 'Confirmar Senha') }}<br>
                                {{ Form::password('password_confirmation', array('class' => 'form-control')) }}
                                
                            </div>
                            
                            {{ Form::submit('Adicionar', array('class' => 'btn btn-primary')) }}
                            
                            {{ Form::close() }}
                            <br>
                        </div>
                        
                        
@stop
                        

resources/views/users/edit.blade.php
@extends('adminlte::page')

@section('title', 'Alterar Usuário')

@section('content_header')
<h3><i class="fa fa-users"></i> Administrador de usuários<h3>
    @stop
    
    @section('content')
    
    <div class="box">
        <div class="box-header">
            <div class="box-body">
                <div class="panel panel-default">
                    <div class="table-responsive">
                        <div class='col-lg-6 col-lg-offset-4'>
                            
                            <h3><i class='fa fa-user-edit'></i> Alterar usuário: {{$user->name}}</h3>
                            
                            @include('admin.includes.alerts')
                            {{ Form::model($user, array('route' => array('users.update', $user->id), 'method' => 'PUT')) }}{{-- Form model binding to automatically populate our fields with user data --}}
                            
                            <div class="form-group">
                                {{ Form::label('name', 'Nome') }}
                                {{ Form::text('name', null, array('class' => 'form-control')) }}
                            </div>
                            
                            <div class="form-group">
                                {{ Form::label('email', 'Email') }}
                                {{ Form::email('email', null, array('class' => 'form-control')) }}
                            </div>
                            
                            <h5><b>Qual papel</b></h5>
                            
                            <div class='form-group'>
                                @foreach ($roles as $role)
                                {{ Form::checkbox('roles[]',  $role->id, $user->roles ) }}
                                {{ Form::label($role->name, ucfirst($role->name)) }}<br>
                                
                                @endforeach
                            </div>
                            
                            <div class="form-group">
                                {{ Form::label('password', 'Password') }}<br>
                                {{ Form::password('password', array('class' => 'form-control')) }}
                                
                            </div>
                            
                            <div class="form-group">
                                {{ Form::label('password', 'Confirm Password') }}<br>
                                {{ Form::password('password_confirmation', array('class' => 'form-control')) }}
                                
                            </div>
                            
                            {{ Form::submit('Add', array('class' => 'btn btn-primary')) }}
                            
                            {{ Form::close() }}
                            <br>
                        </div>
@stop
                        

resources/views/users/index.blade.php
@extends('adminlte::page')

@section('title', 'Usuários')

@section('content_header')
<h3><i class="fa fa-users"></i> Administrador de usuários<h3>
    @stop

    @section('content')
    <div class="box">
        <div class="box-header">
            <div class="box-body">
                @can('Incluir usuários')<a href="{{ route('users.create') }}" class="btn btn-success">Adicionar Usuário</a>@endcan
                @can('Acessar funções')<a href="{{ route('roles.index') }}" class="btn btn-default pull-right">Papéis</a>@endcan
                @can('Acessar permissões')<a href="{{ route('permissions.index') }}" class="btn btn-default pull-right">Permissões</a>@endcan
            </div>
            <div class="box-body">
                <div class="panel panel-default">
                    <div class="panel-heading">Página {{ $users->currentPage() }} de {{ $users->lastPage() }}</div>
                    <div class="table-responsive">
                        <table class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>Nome</th>
                                    <th>Email</th>
                                    <th>Data/Hora Adicionado</th>
                                    <th>Funções do usuário</th>
                                    <th style="width:200px;">Operações</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($users as $user)
                                <tr>
                                    <td>{{ $user->name }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td>{{ $user->created_at->format('F d, Y h:ia') }}</td>
                                    <td>{{  $user->roles()->pluck('name')->implode(' ') }}</td>{{-- Retrieve array of roles associated to a user and convert to string --}}
                                    <td>
                                        @can('Alterar usuários')<a href="{{ route('users.edit', $user->id) }}" class="btn btn-info pull-left" style="margin-right: 3px;">Alterar</a>@endcan
                                        @can('Excluir usuários')
                                        {!! Form::open(['method' => 'DELETE', 'route' => ['users.destroy', $user->id] ]) !!}
                                        {!! Form::submit('Excluir', ['class' => 'btn btn-danger']) !!}
                                        {!! Form::close() !!}
                                        @endcan
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                        <div class="text-center">
                            {!! $users->links() !!}
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>

    @stop