routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

$this->group(['middleware' => ['auth'], 'namespace' => 'Admin', 'prefix' => 'admin'], function () {
    $this->any('historic-search', 'BalanceController@searchHistoric')->name('historic.search');
    $this->get('historic', 'BalanceController@historic')->name('admin.historic');
    $this->get('transfer', 'BalanceController@transfer')->name('balance.transfer');
    $this->post('transfer', 'BalanceController@transferStore')->name('transfer.store');
    $this->post('confirmTransfer', 'balancecontroller@confirmTransfer')->name('confirm.Transfer');
    $this->get('withdraw', 'BalanceController@withdraw')->name('balance.withdraw');
    $this->post('withdraw', 'BalanceController@withdrawStore')->name('withdraw.store');
    $this->get('/', 'AdminController@index')->name('admin.home');
    $this->get('balance', 'BalanceController@index')->name('admin.balance');
    $this->get('deposit', 'BalanceController@deposit')->name('balance.deposit');
    $this->post('deposit', 'BalanceController@depositStore')->name('deposit.store');
    $this->post('atualizar-perfil', 'PerfilController@profileUpdate')->name('profile.update');
    $this->get('meu-perfil', 'PerfilController@profile')->name('profile');
    $this->get('logout', 'PerfilController@logout')->name('logout');
    $this->get('posts', 'PostController@index')->name('posts');

    Route::resource('users', 'UserController');

    Route::resource('roles', 'RoleController');

    Route::resource('permissions', 'PermissionController');

    Route::resource('posts', 'PostController');
});

$this->get('/', 'HomeController@index')->name('home');

Auth::routes();

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use Auth;
//Importing laravel-permission models
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

use Session;

class RoleController extends Controller {

    public function __construct() {
        $this->middleware(['auth', 'isAdmin']);//isAdmin middleware lets only users with a //specific permission permission to access these resources
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $roles = Role::orderby('name')->paginate(8);//Get all roles

        return view('roles.index')->with('roles', $roles);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        $permissions = Permission::all();//Get all permissions

        return view('roles.create', ['permissions'=>$permissions]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
    //Validate name and permissions field
        $this->validate($request, [
            'name'=>'required|unique:roles|max:20',
            'permissions' =>'required',
            ]
        );

        $name = $request['name'];
        $role = new Role();
        $role->name = $name;

        $permissions = $request['permissions'];

        $role->save();
    //Looping thru selected permissions
        foreach ($permissions as $permission) {
            $p = Permission::where('id', '=', $permission)->firstOrFail(); 
         //Fetch the newly created role and assign permission
            $role = Role::where('name', '=', $name)->first(); 
            $role->givePermissionTo($p);
        }

        return redirect()->route('roles.index')
            ->with('flash_message',
             'Role'. $role->name.' added!'); 
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        return redirect('roles');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        $role = Role::findOrFail($id);
        $permissions = Permission::all();

        return view('roles.edit', compact('role', 'permissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {

        $role = Role::findOrFail($id);//Get role with the given id
    //Validate name and permission fields
        $this->validate($request, [
            'name'=>'required|max:20|unique:roles,name,'.$id,
            'permissions' =>'required',
        ]);

        $input = $request->except(['permissions']);
        $permissions = $request['permissions'];
        $role->fill($input)->save();

        $p_all = Permission::all();//Get all permissions

        foreach ($p_all as $p) {
            $role->revokePermissionTo($p); //Remove all permissions associated with role
        }

        foreach ($permissions as $permission) {
            $p = Permission::where('id', '=', $permission)->firstOrFail(); //Get corresponding form //permission in db
            $role->givePermissionTo($p);  //Assign permission to role
        }

        return redirect()->route('roles.index')
            ->with('flash_message',
             'Role'. $role->name.' updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $role = Role::findOrFail($id);
        $role->delete();

        return redirect()->route('roles.index')
            ->with('flash_message',
             'Role deleted!');

    }
}

resources/views/roles/create.blade.php
@extends('adminlte::page')

@section('title', 'Adicionar função')

@section('content_header')
    <h3><i class="fa fa-map"></i> Funções</h3>    
@stop

@section('content')
<div class="box">
    <div class="box-header">
        <div class="box-body">
            <div class="panel panel-default">
                <div class="table-responsive">
                    <div class='col-lg-6 col-lg-offset-4'>
                        
                        <h3><i class='fa fa-key'></i> Adicionar Função</h3>
                        <hr>
                        @include('admin.includes.alerts')
                        {{ Form::open(array('url' => 'admin\roles')) }}
                        
                        <div class="form-group">
                            {{ Form::label('name', 'Nome') }}
                            {{ Form::text('name', null, array('class' => 'form-control')) }}
                        </div>
                        
                        <h5><b>Atribuir Permissões</b></h5>
                        
                        <div class='form-group'>
                            @foreach ($permissions as $permission)
                            {{ Form::checkbox('permissions[]',  $permission->id ) }}
                            {{ Form::label($permission->name, ucfirst($permission->name)) }}<br>
                            
                            @endforeach
                        </div>
                        
                        {{ Form::submit('Adicionar', array('class' => 'btn btn-primary')) }}
                        
                        {{ Form::close() }}
                        <br>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
    
@stop

resources/views/roles/edit.blade.php
@extends('adminlte::page')

@section('title', 'Alterar função')

@section('content_header')
<h3><i class="fa fa-map"></i> Funções</h3>
@stop

@section('content')
<div class="box">
    <div class="box-header">
        <div class="box-body">
            <div class="panel panel-default">
                <div class="table-responsive">
                    <div class='col-lg-6 col-lg-offset-4'>
                        <h3><i class='fa fa-key'></i> Alterar Função: {{$role->name}}</h3>
                        @include('admin.includes.alerts')
                        {{ Form::model($role, array('route' => array('roles.update', $role->id), 'method' => 'PUT')) }}
                        
                        <div class="form-group">
                            {{ Form::label('name', 'Role Name') }}
                            {{ Form::text('name', null, array('class' => 'form-control')) }}
                        </div>
                        
                        <h5><b>Assign Permissions</b></h5>
                        @foreach ($permissions as $permission)
                        
                        {{Form::checkbox('permissions[]',  $permission->id, $role->permissions ) }}
                        {{Form::label($permission->name, ucfirst($permission->name)) }}<br>
                        
                        @endforeach
                        <br>
                        {{ Form::submit('Alterar', array('class' => 'btn btn-primary')) }}
                        
                        {{ Form::close() }} 
                        <br>   
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
                    
@stop
                    

resources/views/roles/index.blade.php
@extends('adminlte::page')

@section('title', 'Papéis')

@section('content_header')
<h3><i class="fa fa-map"></i> Funções</h3>
@stop

@section('content')

<div class="box">
    <div class="box-header">
        <div class="box-body">
            @can('Incluir funções')<a href="{{ URL::to('admin/roles/create') }}" class="btn btn-success">Adicionar função</a>@endcan
            @can('Acessar usuários')<a href="{{ route('users.index') }}" class="btn btn-default pull-right">Usuarios</a>@endcan
            @can('Acessar permissões')<a href="{{ route('permissions.index') }}" class="btn btn-default pull-right">Permissões</a>@endcan
        </div>
        <div class="box-body">
            <div class="panel panel-default">
                <div class="panel-heading">Página {{ $roles->currentPage() }} de {{ $roles->lastPage() }}</div>
                <div class="table-responsive">
                    <table class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Função</th>
                                <th>Permissões</th>
                                <th style="width:200px;">Operações</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach ($roles as $role)
                            <tr>
                                <td>{{ $role->name }}</td>
                                <td>{{ str_replace(array('[',']','"'),'', $role->permissions()->pluck('name')) }}</td>{{-- Retrieve array of permissions associated to a role and convert to string --}}
                                <td>
                                   @can('Alterar funções')<a href="{{ URL::to('admin/roles/'.$role->id.'/edit') }}" class="btn btn-info pull-left" style="margin-right: 3px;">Alterar</a>@endcan
                                   @can('Excluir funções')
                                    {!! Form::open(['method' => 'DELETE', 'route' => ['roles.destroy', $role->id] ]) !!}
                                    {!! Form::submit('Excluir', ['class' => 'btn btn-danger']) !!}
                                    {!! Form::close() !!}
                                    @endcan

                                </td>
                            </tr>
                            @endforeach
                        </tbody>

                    </table>
                    <div class="text-center">
                        {!! $roles->links() !!}
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>


@stop